// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  var WORKING_DIRECTORY, fs, make_absolute, path;
  path = require('path');
  fs = require('fs');
  app.get('/', function(req, res) {
    return res.render('index', {
      action: 'Do Something!'
    });
  });
  WORKING_DIRECTORY = path.resolve('./');
  make_absolute = function(file) {
    var target;
    target = path.join(WORKING_DIRECTORY, file);
    if (target.slice(0, WORKING_DIRECTORY.length) === WORKING_DIRECTORY) {
      return target;
    } else {
      return null;
    }
  };
  app.get(/^\/edit\/(.*)/, function(req, res) {
    var file, readFile, target;
    file = req.params[0];
    target = make_absolute(file);
    if (target != null) {
      readFile = function() {
        return fs.readFile(target, function(err, contents) {
          if (err) {
            if (err.code === 'ENOENT') {
              return res.render('edit', {
                file: file,
                contents: ''
              });
            } else {
              return res.send(400, err);
            }
          } else {
            return res.render('edit', {
              file: file,
              contents: contents
            });
          }
        });
      };
      return fs.stat(target, function(err, stat) {
        if (!err && stat.isDirectory()) {
          return fs.readdir(target, function(err, files) {
            if (err) {
              return readFile();
            } else {
              return res.send(200, files);
            }
          });
        } else {
          return readFile();
        }
      });
    } else {
      return res.send(400, 'Invalid File');
    }
  });
  return app.post(/^\/edit\/(.+)/, function(req, res) {
    var file, target;
    file = req.params[0];
    target = make_absolute(file);
    console.log(req.body);
    if (target != null) {
      return fs.writeFile(target, req.body.content, function(err) {
        if (err) {
          return res.send(400, err);
        } else {
          return res.send({
            okay: true
          });
        }
      });
    } else {
      return res.send(400, 'Invalid File');
    }
  });
};
